import type { AccessRequest, AccessSubmission, EffectiveGrant } from './access.types';

const now = '2026-08-19T10:36:00.000Z';
const applicant = (name: string, department: string) => ({ id: `user-${name}`, name, department });
const scope = (fields: string[], regionNames: string[], operation: AccessRequest['operation'] = 'QUERY') => ({ operation, fields, geography: { regionNames } });

export const ACCESS_SUBMISSIONS: AccessSubmission[] = [
  { id: 'sub-01-aging', taskId: 'task-aging-resource', solutionId: 'solution-aging-resource', taskTitle: '街镇老龄化与养老资源分析', purpose: '分析街镇人口老龄化程度及养老资源覆盖情况。', source: '推荐数据方案', requestIds: ['req-pop-basic', 'rev-001'], createdAt: '2026-08-19T10:18:00.000Z', updatedAt: '2026-08-19T10:36:00.000Z' },
  { id: 'sub-02-structure', taskId: 'task-population-trend', solutionId: 'solution-population-trend', taskTitle: '各街镇人口结构趋势分析', purpose: '测算近三年各街镇不同年龄梯队人口变动比例与抚养比。', source: '推荐数据方案', requestIds: ['req-pop-history', 'req-region-geo'], createdAt: '2026-08-18T16:40:00.000Z', updatedAt: '2026-08-19T09:30:00.000Z' },
  { id: 'sub-03-care', taskId: 'task-community-care', solutionId: 'solution-community-care', taskTitle: '社区养老服务供给分析', purpose: '评估各社区助餐点、日间照料中心的服务半径与覆盖效能。', source: '目标搜数推荐', requestIds: ['req-care-sites'], createdAt: '2026-08-14T14:20:00.000Z', updatedAt: '2026-08-15T11:05:00.000Z' },
  { id: 'sub-04-offline', taskId: 'task-offline-aging', solutionId: 'solution-offline-aging', taskTitle: '老龄化率专题离线分析', purpose: '申请常住人口明细及迁移人口底册进行离线专题建模。', source: '自主方案构建', requestIds: ['req-pop-export', 'req-aging-metric'], createdAt: '2026-08-12T09:10:00.000Z', updatedAt: '2026-08-13T17:30:00.000Z' },
  { id: 'sub-05-business', taskId: 'task-business', solutionId: 'solution-business', taskTitle: '企业主体活跃度分析', purpose: '用于营商环境评估调研中的企业回访样本抽样。', source: '推荐数据方案', requestIds: ['rev-002'], createdAt: '2026-08-19T10:13:00.000Z', updatedAt: '2026-08-19T10:13:00.000Z' },
  { id: 'sub-06-api', taskId: 'task-api-care', solutionId: 'solution-api-care', taskTitle: '社区养老服务供给分析（实时）', purpose: '为社区养老数字看板提供实时设施点位和负荷数据。', source: '目标搜数推荐', requestIds: ['rev-003'], createdAt: '2026-08-19T09:48:00.000Z', updatedAt: '2026-08-19T09:48:00.000Z' },
  { id: 'sub-07-export', taskId: 'task-export-study', solutionId: 'solution-export-study', taskTitle: '老龄化专题离线分析', purpose: '支撑人口规划中期评估模型线下仿真测算。', source: '自主方案构建', requestIds: ['rev-004'], createdAt: '2026-08-19T08:54:00.000Z', updatedAt: '2026-08-19T08:54:00.000Z' },
  { id: 'sub-08-elderly', taskId: 'task-elderly-care', solutionId: 'solution-elderly-care', taskTitle: '独居高龄老人关爱服务专项', purpose: '匹配社区志愿者结对帮扶与紧急呼叫铃加装工作。', source: '推荐数据方案', requestIds: ['rev-005'], createdAt: '2026-08-18T17:20:00.000Z', updatedAt: '2026-08-18T17:20:00.000Z' },
];

export const ACCESS_REQUESTS: AccessRequest[] = [
  {
    id: 'req-pop-basic', submissionId: 'sub-01-aging', taskId: 'task-aging-resource', solutionId: 'solution-aging-resource', resourceId: 'res-view-pop-basic', resourceName: '人口基本信息视图', resourceType: 'DATA_ASSET_VIEW', required: true, operation: 'QUERY', requestedScope: scope(['年龄与出生信息', '常住状态', '行政区域'], ['闵行区']), state: 'GRANTED_WITH_LIMITS', applicant: applicant('张明', '人口分析部门'), purpose: '分析街镇人口老龄化程度及养老资源覆盖情况。', riskLevel: 'MEDIUM', requestedDurationDays: 90, policyProfile: 'PERSONAL_DATA', resourceOwnerTeam: '人口业务数据责任团队',
    fieldDetails: [{ businessName: '年龄与出生信息', technicalName: 'age_birth_info', treatment: 'ALLOW' }, { businessName: '常住状态', technicalName: 'resident_status', treatment: 'ALLOW' }, { businessName: '行政区域', technicalName: 'administrative_region', treatment: 'ALLOW' }, { businessName: '姓名', technicalName: 'person_name', treatment: 'MASK', sensitivity: '直接标识信息' }, { businessName: '身份证号', technicalName: 'id_card_no', treatment: 'EXCLUDE', sensitivity: '敏感身份信息' }, { businessName: '联系方式', technicalName: 'mobile_phone', treatment: 'EXCLUDE', sensitivity: '联系方式' }], submittedAt: '2026-08-19T10:18:00.000Z', updatedAt: now,
  },
  {
    id: 'rev-001', submissionId: 'sub-01-aging', taskId: 'task-aging-resource', solutionId: 'solution-aging-resource', resourceId: 'res-asset-elderly-org', resourceName: '养老机构基本信息', resourceType: 'DATA_ASSET', required: true, operation: 'QUERY', requestedScope: scope(['机构名称', '机构位置', '核定床位数', '服务类型'], ['闵行区']), state: 'PENDING_REVIEW', applicant: applicant('张明', '人口分析部门'), purpose: '分析街镇人口老龄化程度及养老资源覆盖情况。', reviewReason: '机构空间位置和服务能力数据需要确认最小必要访问范围。', riskLevel: 'MEDIUM', requestedDurationDays: 90, policyProfile: 'BUSINESS_DATA', resourceOwnerTeam: '养老业务数据责任团队',
    fieldDetails: [{ businessName: '机构名称', technicalName: 'facility_name', treatment: 'ALLOW' }, { businessName: '机构位置', technicalName: 'location_code', treatment: 'ALLOW' }, { businessName: '核定床位数', technicalName: 'approved_beds', treatment: 'ALLOW' }, { businessName: '服务类型', technicalName: 'service_type', treatment: 'ALLOW' }], submittedAt: '2026-08-19T10:36:00.000Z', updatedAt: now,
  },
  { id: 'req-pop-history', submissionId: 'sub-02-structure', taskId: 'task-population-trend', solutionId: 'solution-population-trend', resourceId: 'res-history-pop', resourceName: '历年人口变动统计表', resourceType: 'DATA_ASSET', required: true, operation: 'QUERY', requestedScope: scope(['统计年份', '街镇编码', '年龄区间', '常住人口汇总数'], ['闵行区']), state: 'GRANTED', applicant: applicant('刘敏', '人口分析部门'), purpose: '测算近三年各街镇人口变动比例与抚养比。', riskLevel: 'LOW', requestedDurationDays: 90, policyProfile: 'BUSINESS_DATA', resourceOwnerTeam: '人口业务数据责任团队', submittedAt: '2026-08-18T16:40:00.000Z', updatedAt: '2026-08-19T09:30:00.000Z' },
  { id: 'req-region-geo', submissionId: 'sub-02-structure', taskId: 'task-population-trend', solutionId: 'solution-population-trend', resourceId: 'res-region-geo', resourceName: '行政区划基础数据', resourceType: 'DATA_ASSET', required: true, operation: 'QUERY', requestedScope: scope(['区划代码', '街镇名称', '地理边界'], ['闵行区']), state: 'GRANTED', applicant: applicant('刘敏', '人口分析部门'), purpose: '测算近三年各街镇人口变动比例与抚养比。', riskLevel: 'LOW', requestedDurationDays: 365, policyProfile: 'BUSINESS_DATA', resourceOwnerTeam: '基础地理数据责任团队', submittedAt: '2026-08-18T16:40:00.000Z', updatedAt: '2026-08-19T09:30:00.000Z' },
  { id: 'req-care-sites', submissionId: 'sub-03-care', taskId: 'task-community-care', solutionId: 'solution-community-care', resourceId: 'res-care-sites', resourceName: '社区助老服务网点明细', resourceType: 'DATA_ASSET', required: true, operation: 'QUERY', requestedScope: scope(['网点名称', '街道社区归属', '空间位置', '供餐能力'], ['全区各社区']), state: 'GRANTED_WITH_LIMITS', applicant: applicant('王斌', '民政服务组'), purpose: '评估社区养老服务半径与覆盖效能。', riskLevel: 'MEDIUM', requestedDurationDays: 90, policyProfile: 'BUSINESS_DATA', resourceOwnerTeam: '民政业务数据责任团队', submittedAt: '2026-08-14T14:20:00.000Z', updatedAt: '2026-08-15T11:05:00.000Z' },
  { id: 'req-pop-export', submissionId: 'sub-04-offline', taskId: 'task-offline-aging', solutionId: 'solution-offline-aging', resourceId: 'res-pop-export', resourceName: '全员人口底册明细', resourceType: 'DATA_ASSET', required: true, operation: 'EXPORT', requestedScope: scope(['人口原始明细', '身份证号', '手机号'], ['全区'], 'EXPORT'), state: 'DENIED', applicant: applicant('陈蕾', '政策研究室'), purpose: '进行离线数仓重构与专题建模。', reviewReason: '离线导出受保护数据需要更严格的使用边界。', riskLevel: 'HIGH', requestedDurationDays: 7, policyProfile: 'EXPORT_DATA', resourceOwnerTeam: '人口业务数据责任团队', submittedAt: '2026-08-12T09:10:00.000Z', updatedAt: '2026-08-13T17:30:00.000Z' },
  { id: 'req-aging-metric', submissionId: 'sub-04-offline', taskId: 'task-offline-aging', solutionId: 'solution-offline-aging', resourceId: 'res-aging-metric', resourceName: '老龄人口判定指标口径字典', resourceType: 'METRIC', required: false, operation: 'QUERY', requestedScope: scope(['标准口径名称', '计算逻辑'], ['全区']), state: 'GRANTED', applicant: applicant('陈蕾', '政策研究室'), purpose: '进行离线数仓重构与专题建模。', riskLevel: 'LOW', requestedDurationDays: 365, policyProfile: 'BUSINESS_DATA', resourceOwnerTeam: '人口业务数据责任团队', submittedAt: '2026-08-12T09:10:00.000Z', updatedAt: '2026-08-13T17:30:00.000Z' },
  {
    id: 'rev-002', submissionId: 'sub-05-business', taskId: 'task-business', solutionId: 'solution-business', resourceId: 'res-view-corp-contact', resourceName: '法人联系方式视图', resourceType: 'DATA_ASSET_VIEW', required: true, operation: 'QUERY', requestedScope: scope(['企业名称', '法人姓名', '注册区县'], ['全市']), state: 'PENDING_REVIEW', applicant: applicant('李倩', '营商分析组'), purpose: '用于营商环境评估调研中的企业回访样本抽样。', reviewReason: '包含联系方式信息，需要确认最小必要访问范围。', riskLevel: 'MEDIUM', requestedDurationDays: 30, policyProfile: 'PERSONAL_DATA', resourceOwnerTeam: '企业服务数据责任团队',
    fieldDetails: [{ businessName: '企业名称', technicalName: 'company_name', treatment: 'ALLOW' }, { businessName: '法人姓名', technicalName: 'legal_representative_name', treatment: 'MASK', sensitivity: '直接标识信息' }, { businessName: '注册区县', technicalName: 'registered_district', treatment: 'ALLOW' }, { businessName: '联系方式', technicalName: 'contact_phone', treatment: 'EXCLUDE', sensitivity: '联系方式' }], submittedAt: '2026-08-19T10:13:00.000Z', updatedAt: '2026-08-19T10:13:00.000Z',
  },
  {
    id: 'rev-003', submissionId: 'sub-06-api', taskId: 'task-api-care', solutionId: 'solution-api-care', resourceId: 'res-api-community-care', resourceName: '社区养老服务查询 API', resourceType: 'DATA_API', required: true, operation: 'INVOKE', requestedScope: scope(['设施点位', '可用床位', '服务状态'], ['全区'], 'INVOKE'), state: 'PENDING_REVIEW', applicant: applicant('王斌', '民政服务组'), purpose: '为社区养老数字看板提供实时设施点位与负荷数据。', reviewReason: '跨组织调用，需要确认流控配额与授权期限。', riskLevel: 'LOW', requestedDurationDays: 180, policyProfile: 'API_SERVICE', resourceOwnerTeam: '民政服务平台责任团队',
    fieldDetails: [{ businessName: '设施点位', technicalName: 'facility_location', treatment: 'ALLOW' }, { businessName: '可用床位', technicalName: 'available_beds', treatment: 'ALLOW' }, { businessName: '服务状态', technicalName: 'service_status', treatment: 'ALLOW' }], submittedAt: '2026-08-19T09:48:00.000Z', updatedAt: '2026-08-19T09:48:00.000Z',
  },
  {
    id: 'rev-004', submissionId: 'sub-07-export', taskId: 'task-export-study', solutionId: 'solution-export-study', resourceId: 'res-view-pop-basic-export', resourceName: '人口基础数据离线导出', resourceType: 'DATA_ASSET_VIEW', required: true, operation: 'EXPORT', requestedScope: scope(['人口统计明细', '街道与居委粒度'], ['全市'], 'EXPORT'), state: 'PENDING_REVIEW', applicant: applicant('陈蕾', '政策研究室'), purpose: '支撑人口规划中期评估模型线下仿真测算。', reviewReason: '高风险离线导出操作，需要确认受控环境和用途。', riskLevel: 'HIGH', requestedDurationDays: 7, policyProfile: 'EXPORT_DATA', resourceOwnerTeam: '人口业务数据责任团队',
    fieldDetails: [{ businessName: '人口统计明细', technicalName: 'population_detail', treatment: 'ALLOW', sensitivity: '受保护统计明细' }, { businessName: '街道与居委粒度', technicalName: 'subdistrict_committee_level', treatment: 'ALLOW', sensitivity: '细粒度空间信息' }], submittedAt: '2026-08-19T08:54:00.000Z', updatedAt: '2026-08-19T08:54:00.000Z',
  },
  {
    id: 'rev-005', submissionId: 'sub-08-elderly', taskId: 'task-elderly-care', solutionId: 'solution-elderly-care', resourceId: 'res-view-aging-dist', resourceName: '老龄重点关注人群', resourceType: 'DATA_ASSET_VIEW', required: true, operation: 'QUERY', requestedScope: scope(['社区编码', '高龄分布', '照护等级'], ['浦东新区']), state: 'PENDING_REVIEW', applicant: applicant('赵宇', '民政服务组'), purpose: '匹配社区志愿者结对帮扶与紧急呼叫铃加装工作。', reviewReason: '涉及重点关注人群，需要确认最小知悉范围。', riskLevel: 'MEDIUM', requestedDurationDays: 60, policyProfile: 'SPECIAL_POPULATION', resourceOwnerTeam: '民政业务数据责任团队',
    fieldDetails: [{ businessName: '社区编码', technicalName: 'community_code', treatment: 'MASK', sensitivity: '空间精度' }, { businessName: '高龄分布', technicalName: 'elderly_distribution', treatment: 'ALLOW' }, { businessName: '照护等级', technicalName: 'care_level', treatment: 'ALLOW', sensitivity: '特殊群体信息' }, { businessName: '直接联系方式', technicalName: 'contact_phone', treatment: 'EXCLUDE', sensitivity: '联系方式' }], submittedAt: '2026-08-18T17:20:00.000Z', updatedAt: '2026-08-18T17:20:00.000Z',
  },
];

const grant = (id: string, requestId: string, resourceId: string, fields: string[], expiresAt: string, protections: EffectiveGrant['protections'] = [], restrictions: EffectiveGrant['restrictions'] = []): EffectiveGrant => ({ id, requestId, resourceId, state: 'ACTIVE', scope: scope(fields, ['闵行区']), protections, restrictions, effectiveAt: '2026-08-18T09:00:00.000Z', expiresAt });

export const EFFECTIVE_GRANTS: EffectiveGrant[] = [
  grant('grant-pop-basic', 'req-pop-basic', 'res-view-pop-basic', ['年龄与出生信息', '常住状态', '行政区域'], '2026-11-17T00:00:00.000Z', [{ id: 'grant-pop-basic-mask', type: 'MASK', target: '姓名', description: '姓名采用动态脱敏展示' }, { id: 'grant-pop-basic-exclude', type: 'EXCLUDE', target: '身份证号、联系方式', description: '身份证号和联系方式不可访问' }, { id: 'grant-pop-basic-audit', type: 'AUDIT', description: '所有访问调用均纳入审计' }], [{ id: 'grant-pop-basic-online', description: '仅限在线查询，不允许导出' }]),
  grant('grant-pop-history', 'req-pop-history', 'res-history-pop', ['统计年份', '街镇编码', '年龄区间', '常住人口汇总数'], '2026-11-16T00:00:00.000Z'),
  grant('grant-region-geo', 'req-region-geo', 'res-region-geo', ['区划代码', '街镇名称', '地理边界'], '2027-08-16T00:00:00.000Z'),
  grant('grant-care-sites', 'req-care-sites', 'res-care-sites', ['网点名称', '街道社区归属', '空间位置'], '2026-11-14T00:00:00.000Z', [{ id: 'grant-care-sites-scope', type: 'ROW_FILTER', description: '限定已授权区域与任务必要字段' }, { id: 'grant-care-sites-audit', type: 'AUDIT', description: '所有访问调用均纳入审计' }], [{ id: 'grant-care-sites-online', description: '仅限在线查询，不允许导出' }]),
  grant('grant-aging-metric', 'req-aging-metric', 'res-aging-metric', ['标准口径名称', '计算逻辑'], '2027-08-12T00:00:00.000Z'),
];
