import React, { useState } from 'react';
import { ArrowLeft, Check, ChevronDown, Clock, ExternalLink, FileText, Info, ShieldAlert, ShieldCheck, SlidersHorizontal, X } from 'lucide-react';
import { AdminCenterShell, type AdminCenterItem } from './AdminCenterShell';
import { buildAccessRecommendation } from '../domain/access/accessDecision';
import { useAccessRequest, useAccessStore, useAccessSubmission, useEffectiveGrant } from '../domain/access/access.store';
import type { EffectiveGrant } from '../domain/access/access.types';

export interface AccessReviewDetailWorkspaceProps {
  requestId?: string;
  onBackToQueue?: () => void;
  onNavigateToAuthorizationRecords?: () => void;
  onNavigateToPolicyManagement?: () => void;
  onNavigateToAuditLogs?: () => void;
  onDecisionComplete?: () => void;
  addToast?: (type: 'success' | 'error' | 'info', title: string, message: string) => void;
}

const operationLabel = (operation: string) => ({ QUERY: '查询数据', EXPORT: '导出数据', INVOKE: '调用服务', SUBSCRIBE: '订阅更新' }[operation] ?? operation);

export const AccessReviewDetailWorkspace: React.FC<AccessReviewDetailWorkspaceProps> = ({ requestId, onBackToQueue, onNavigateToAuthorizationRecords, onNavigateToPolicyManagement, onNavigateToAuditLogs, onDecisionComplete, addToast }) => {
  const request = useAccessRequest(requestId);
  const submission = useAccessSubmission(request?.submissionId);
  const grant = useEffectiveGrant(request?.id);
  const { decideRequest } = useAccessStore();
  const [fieldsOpen, setFieldsOpen] = useState(false);
  const [customOpen, setCustomOpen] = useState(false);
  const [denyOpen, setDenyOpen] = useState(false);
  const [duration, setDuration] = useState(90);
  const [region, setRegion] = useState('推荐区域');
  const [denyReason, setDenyReason] = useState('申请范围超出当前任务所需');
  if (!request) return <AdminCenterShell activeItem="access-review"><main className="grid flex-1 place-items-center text-sm text-[#667085]">未找到对应的访问申请。</main></AdminCenterShell>;
  const recommendation = buildAccessRecommendation(request);
  const fields = request.requestedScope.fields ?? [];
  const scope = request.requestedScope.geography?.regionNames?.join('、') ?? '已核定区域';
  const navigate = (item: AdminCenterItem) => { if (item === 'access-review') onBackToQueue?.(); if (item === 'authorization-records') onNavigateToAuthorizationRecords?.(); if (item === 'policies') onNavigateToPolicyManagement?.(); if (item === 'audit-logs') onNavigateToAuditLogs?.(); };
  const complete = (decision: 'GRANT' | 'GRANT_WITH_LIMITS' | 'DENY', customGrant?: EffectiveGrant, reason?: string) => {
    decideRequest({ requestId: request.id, decision, grant: customGrant, reason });
    addToast?.(decision === 'DENY' ? 'info' : 'success', decision === 'DENY' ? '已拒绝访问申请' : '访问决策已完成', `已写入本次访问决策，并重新计算「${submission?.taskTitle ?? request.purpose}」的任务状态。`);
    onDecisionComplete?.();
    onBackToQueue?.();
  };
  const approveRecommended = () => complete(recommendation.recommendation, undefined, '按系统建议授权');
  const approveCustom = () => {
    const customGrant: EffectiveGrant = { id: `grant-${request.id}-custom-${Date.now()}`, requestId: request.id, resourceId: request.resourceId, state: 'ACTIVE', scope: { ...request.requestedScope, geography: { regionNames: [region] } }, protections: recommendation.protections, restrictions: recommendation.restrictions, effectiveAt: new Date().toISOString(), expiresAt: new Date(Date.now() + duration * 864e5).toISOString() };
    setCustomOpen(false); complete('GRANT_WITH_LIMITS', customGrant, '审核人调整限制后授权');
  };

  return <AdminCenterShell activeItem="access-review" onNavigate={navigate}><main className="flex flex-1 flex-col overflow-hidden bg-[#F7F9FC]"><div className="flex-1 overflow-y-auto"><div className="mx-auto max-w-7xl space-y-5 p-6 lg:p-8">
    <header className="space-y-3"><div className="flex items-center justify-between"><button onClick={onBackToQueue} className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#2563EB]"><ArrowLeft className="h-3.5 w-3.5" />返回访问审核列表</button><span className="text-xs text-[#98A2B3]">管理中心 / 权限管理 / 访问审核</span></div><div><div className="flex flex-wrap items-center gap-2.5"><h1 className="text-2xl font-bold">{request.resourceName} · 访问申请</h1><span className="inline-flex items-center gap-1 rounded border border-[#FDE68A] bg-[#FFFBEB] px-2 py-0.5 text-xs font-bold text-[#B45309]"><Clock className="h-3 w-3" />待人工确认</span></div><div className="mt-3 rounded-lg border border-[#E6EAF0] bg-white px-5 py-4"><div className="text-[11px] text-[#667085]">需要你确认</div><div className="mt-1 text-sm font-semibold leading-relaxed text-[#172033]">是否允许{request.applicant.name}在未来 {request.requestedDurationDays ?? 90} 天内，以受控{operationLabel(request.operation)}方式访问{scope}的{fields.join('、')}。</div><div className="mt-1 text-xs text-[#667085]">用于：{submission?.taskTitle ?? request.purpose}</div></div></div></header>
    <div className="grid grid-cols-1 gap-6 lg:grid-cols-12"><div className="space-y-5 lg:col-span-8">
      <section className="rounded-lg border border-[#E6EAF0] bg-white p-5"><div className="mb-4 flex items-center gap-2"><span className="grid h-6 w-6 place-items-center rounded bg-[#EFF6FF] text-xs font-bold text-[#2563EB]">01</span><h2 className="text-sm font-bold">申请摘要</h2></div><div className="grid grid-cols-2 gap-4 text-xs sm:grid-cols-4"><div><div className="text-[#98A2B3]">申请人</div><div className="mt-1 font-bold">{request.applicant.name}</div><div className="text-[#667085]">{request.applicant.department}</div></div><div><div className="text-[#98A2B3]">申请动作</div><div className="mt-1 font-bold text-[#2563EB]">{operationLabel(request.operation)}</div></div><div><div className="text-[#98A2B3]">使用期限</div><div className="mt-1 font-bold">{request.requestedDurationDays ?? 90} 天</div></div><div><div className="text-[#98A2B3]">来源</div><div className="mt-1 font-bold">{submission?.source ?? '访问申请'}</div></div></div><div className="mt-4 border-t border-[#EEF2F6] pt-3 text-xs text-[#475569]"><strong>任务用途：</strong>{request.purpose}</div></section>
      <section className="rounded-lg border border-[#E6EAF0] bg-white p-5"><div className="mb-3 flex items-center gap-2"><span className="grid h-6 w-6 place-items-center rounded bg-[#EFF6FF] text-xs font-bold text-[#2563EB]">02</span><h2 className="text-sm font-bold">你需要决定什么</h2></div><p className="text-xs leading-relaxed text-[#475569]">确认该申请是否可以在最小必要范围内授予访问权，并确认系统建议的保护措施与使用限制是否适用。</p><div className="mt-3 flex flex-wrap gap-2">{fields.map((field) => <span key={field} className="rounded border border-[#CBD5E1] bg-[#F8FAFC] px-2 py-1 text-xs">{field}</span>)}</div></section>
      <section className="rounded-lg border border-[#BFDBFE] bg-white p-5"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><span className="grid h-6 w-6 place-items-center rounded bg-[#EFF6FF] text-xs font-bold text-[#2563EB]">03</span><ShieldCheck className="h-4 w-4 text-[#2563EB]" /><div><div className="text-[11px] font-bold text-[#2563EB]">系统建议</div><h2 className="text-base font-bold">{recommendation.recommendation === 'GRANT_WITH_LIMITS' ? '附带限制授权' : recommendation.recommendation === 'GRANT' ? '建议授权' : '建议不授权'}</h2></div></div></div><p className="mb-3 text-xs leading-relaxed text-[#475569]">允许{request.applicant.name}在完成当前分析所需的最小范围内访问数据，并排除与任务无关的敏感身份和联系方式信息。</p><div className="grid gap-3 border-t border-[#EEF2F6] pt-3 text-xs sm:grid-cols-2"><div><div className="text-[#98A2B3]">范围</div><div className="mt-1 font-semibold">{scope}</div></div><div><div className="text-[#98A2B3]">期限</div><div className="mt-1 font-semibold">{request.requestedDurationDays ?? 90} 天</div></div><div><div className="text-[#98A2B3]">允许</div><div className="mt-1">{fields.join('、')}</div></div><div><div className="text-[#98A2B3]">保护</div><div className="mt-1">{recommendation.protections.map((item) => item.description).join('；')}</div></div><div className="sm:col-span-2 rounded bg-[#F8FAFC] p-3"><div className="text-[#98A2B3]">限制</div><div className="mt-1">{recommendation.restrictions.map((item) => item.description).join('；')}；纳入审计</div></div></div><div className="mt-4 border-t border-[#EEF2F6] pt-3 text-xs"><div className="mb-2 font-bold">为什么这样建议</div>{recommendation.evidence.slice(0, 3).map((item) => <div key={item.type} className="mt-1 text-[#475569]">✓ {item.description}</div>)}</div></section>
      <section className="rounded-lg border border-[#E6EAF0] bg-white p-5"><div className="mb-3 flex items-center gap-2"><span className="grid h-6 w-6 place-items-center rounded bg-[#EFF6FF] text-xs font-bold text-[#2563EB]">04</span><h2 className="text-sm font-bold">决策证据</h2></div><div className="space-y-2">{recommendation.evidence.map((item) => <div key={item.type} className="rounded bg-[#F8FAFC] p-3 text-xs"><strong className="text-[#334155]">{item.type}：</strong><span className="text-[#475569]">{item.description}</span></div>)}</div><div className="mt-4 rounded border border-[#E6EAF0] p-3"><div className="text-xs font-bold">详细数据范围</div><div className="mt-1 text-xs text-[#667085]">允许 {fields.length} 项 · 脱敏 {recommendation.protections.filter((item) => item.type === 'MASK').length} 项 · 排除 {recommendation.protections.filter((item) => item.type === 'EXCLUDE').length} 项</div><button onClick={() => setFieldsOpen((open) => !open)} className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-[#2563EB]">{fieldsOpen ? '收起详细字段范围' : '查看详细字段范围'}<ChevronDown className={`h-3.5 w-3.5 ${fieldsOpen ? 'rotate-180' : ''}`} /></button></div>{fieldsOpen && <div className="mt-3 overflow-hidden rounded border border-[#E6EAF0]"><table className="w-full text-left text-xs"><thead className="bg-[#F8FAFC] text-[#667085]"><tr><th className="p-3">业务信息</th><th className="p-3">技术字段</th><th className="p-3">建议处理</th></tr></thead><tbody>{fields.map((field) => <tr key={field} className="border-t border-[#EEF2F6]"><td className="p-3">{field}</td><td className="p-3 font-mono text-[#667085]">{field}</td><td className="p-3 text-[#15803D]">允许</td></tr>)}{recommendation.protections.map((item) => <tr key={item.id} className="border-t border-[#EEF2F6]"><td className="p-3">{item.target ?? '访问保护'}</td><td className="p-3 font-mono text-[#667085]">—</td><td className="p-3 text-[#B45309]">{item.description}</td></tr>)}</tbody></table></div>}</section>
    </div><aside className="space-y-4 lg:col-span-4"><section className="rounded-lg border border-[#E6EAF0] bg-white p-4 text-xs"><h2 className="font-bold">决策上下文</h2><div className="mt-4 space-y-4"><div><div className="text-[#98A2B3]">触发原因</div><p className="mt-1 text-[#475569]">{recommendation.triggerReason}</p></div><div className="border-t border-[#EEF2F6] pt-3"><div className="text-[#98A2B3]">当前策略</div><p className="mt-1 font-semibold">{recommendation.policySummary}</p></div><div className="border-t border-[#EEF2F6] pt-3"><div className="text-[#98A2B3]">风险边界</div><p className="mt-1 text-[#475569]">{recommendation.riskSummary}</p></div><div className="border-t border-[#EEF2F6] pt-3"><div className="text-[#98A2B3]">当前已有授权</div><p className="mt-1 text-[#475569]">{grant ? '已有生效授权' : '无正式访问授权'}</p></div></div></section><section className="rounded-lg border border-[#BFDBFE] bg-[#FAFCFF] p-4 text-xs"><div className="flex items-center gap-2 font-bold text-[#2563EB]"><Info className="h-3.5 w-3.5" />Xino 辅助校验</div><p className="mt-2 leading-relaxed text-[#475569]">在当前建议限制下，未发现与个人信息最小必要及统计分析用途明显冲突的条件。最终授权范围仍由审核人确认。</p></section></aside></div>
  </div></div><footer className="flex flex-col justify-between gap-3 border-t border-[#E6EAF0] bg-white px-6 py-4 sm:flex-row sm:items-center"><div className="text-xs text-[#667085]"><span className="mr-2 inline-grid h-5 w-5 place-items-center rounded bg-[#EFF6FF] font-bold text-[#2563EB]">05</span><Info className="mr-1 inline h-4 w-4 text-[#2563EB]" />当前决定将在授权生效前再次经过策略校验。</div><div className="flex gap-2"><button onClick={() => setDenyOpen(true)} className="rounded border border-[#FECDCA] px-3 py-2 text-xs font-bold text-[#B91C1C]">不授权</button><button onClick={() => setCustomOpen(true)} className="rounded border border-[#CBD5E1] px-3 py-2 text-xs font-bold"><SlidersHorizontal className="mr-1 inline h-3.5 w-3.5" />调整限制并授权</button><button onClick={approveRecommended} className="rounded bg-[#2563EB] px-4 py-2 text-xs font-bold text-white"><Check className="mr-1 inline h-3.5 w-3.5" />按建议授权</button></div></footer></main>
  {customOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-[#0F172A]/40 p-4"><div className="w-full max-w-md space-y-4 rounded-lg bg-white p-6 shadow-xl"><div><h3 className="font-bold">调整授权限制</h3><p className="mt-1 text-xs text-[#667085]">仅在审核人确认需要变化时修改有效期和数据范围。</p></div><div className="grid grid-cols-2 gap-3 text-xs"><label>有效期限<select value={duration} onChange={(event) => setDuration(Number(event.target.value))} className="mt-1 w-full rounded border border-[#E2E8F0] p-2"><option value={30}>30 天</option><option value={90}>90 天</option><option value={180}>180 天</option></select></label><label>数据范围<select value={region} onChange={(event) => setRegion(event.target.value)} className="mt-1 w-full rounded border border-[#E2E8F0] p-2"><option value={scope}>{scope}</option><option value="浦东新区">浦东新区</option><option value="全市辖区">全市辖区</option></select></label></div><div className="rounded border border-[#E6EAF0] bg-[#F8FAFC] p-3 text-xs text-[#475569]"><div><strong>数据保护：</strong>人口分析标准保护策略</div><div className="mt-1">{recommendation.protections.map((item) => item.description).join('；')}</div><div className="mt-2"><strong>数据导出：</strong>不允许</div></div><div className="flex justify-end gap-2"><button onClick={() => setCustomOpen(false)} className="px-3 py-2 text-xs">取消</button><button onClick={approveCustom} className="rounded bg-[#2563EB] px-3 py-2 text-xs font-bold text-white">按调整后方案授权</button></div></div></div>}
  {denyOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-[#0F172A]/40 p-4"><div className="w-full max-w-md space-y-4 rounded-lg bg-white p-6 shadow-xl"><div className="flex items-center gap-2 text-[#B91C1C]"><ShieldAlert className="h-5 w-5" /><h3 className="font-bold">不授权当前访问请求</h3></div><label className="block text-xs">不授权原因<select value={denyReason} onChange={(event) => setDenyReason(event.target.value)} className="mt-1 w-full rounded border border-[#E2E8F0] p-2"><option>申请范围超出当前任务所需</option><option>不符合受保护数据资源使用政策</option><option>高风险操作未满足必要安全条件</option></select></label><div className="flex justify-end gap-2"><button onClick={() => setDenyOpen(false)} className="px-3 py-2 text-xs">取消</button><button onClick={() => complete('DENY', undefined, denyReason)} className="rounded bg-[#B91C1C] px-3 py-2 text-xs font-bold text-white">确认不授权</button></div></div></div>}
  </AdminCenterShell>;
};
